### ISSUE TITLE
Actualizar la documentación de la API

### ISSUE THREAD

**Issue by pabreblob** [pabreblob/decide-io#10]
**¿Su sugerencia está relacionada con algún problema? Por favor descríbalo.**
Al haberse añadido nuevas funcionalidades, es necesario actualizar la documentación de la API que se ofrece.

**Describa una solución que le gustaría ver**
Se añadirá la información relativa a las nuevas funcionalidades, siguiendo un formato similar al ya existente, que permita a quien la lea realizar peticiones con el formato adecuado para utilizar estas nuevas funciones.

**Describa alternativas que haya considerado**
No se han considerado otras alternativas.

**Información adicional**
Preferiblemente cada integrante del grupo se encargará de actualizar la documentación de la API añadiendo información sobre las funcionalidades en las que él ha trabajado.

**Comment by carsevbarus** [comment]
Borda count added in this [commit](https://github.com/pabreblob/decide-io/commit/a9c3b02553c3c94b6625b2ffbecb9f399511ebcd)
