### ISSUE TITLE
Despliegue en Heroku

### ISSUE THREAD

**Issue by pabreblob** [pabreblob/decide-io#5]
**¿Su sugerencia está relacionada con algún problema? Por favor descríbalo.**
Para poder acceder a la aplicación en funcionamiento, será necesario el desplegarla.

**Describa una solución que le gustaría ver**
Se deberá crear una aplicación en Heroku y añadir los ficheros necesarios al proyecto para que éste pueda ser desplegado. También se harán los cambios necesarios para automatizar el proceso de despliegue cada vez que se añadan cambios a la rama principal

**Describa alternativas que haya considerado**
No se consideran otras alternativas.

**Información adicional**
El despliegue automático de la aplicación se hará usando travis. Sólo se desplegará el código que se encuentra en la rama principal.

**Comment by carsevbarus** [comment]
This issue is complete
